### ISSUE TITLE
Style Background Image Url

### ISSUE THREAD

**Issue by blvckbeard1337** [creativeorange/craft-article#19]
Hello, 

I created a block for plugin, 
But unfortunately background url its not working, in the first time its shows good,
![image](https://user-images.githubusercontent.com/69844291/175493676-4c52b0b4-eb50-4309-9b1e-941493a51fdb.png)

but then html purifier add &qout; at the attribute (normal behavior) and after editing article convert background url to unknown path
![image](https://user-images.githubusercontent.com/69844291/175493775-25aa56b4-dc04-420c-bbec-7ab22a2ab0e1.png)

So the problem is we can't edit its work only on create.
Can I disable html purifier and how, or can you give me another solution.

Thanks

**Comment by dejury** [comment]
Hi @blvckbeard1337 

Thanks for using the plugin and reporting this issue.
It is possible to disable the HTML purifier, see screenshot attached. You can do this at the field setup.

Can you please verify if turning this off solves the problem? 
Afterwards I would like to receive the exact block that you are trying to generate, because in my opinion it is better to fix this problem to work with the HTML purifier.

<img width="929" alt="Schermafbeelding 2022-08-03 om 15 16 29" src="https://user-images.githubusercontent.com/16034333/182617625-ce78af5b-f68f-496c-b4be-b5adc4220a6b.png">


Thanks!

**Comment by blvckbeard1337** [comment]
Hi @dejury,

I fix it by disabling html purifier , the block was designed to create a tag with a background image url.
If you create and save it works but if you want to edit html purifer saved code and the plugin reader from previous saved crash on &qout; thing. 

You can mark as closed as by now I found a solution. The main problem is not closed if somebody want background image url and html purifier it will not work.

Thanks,

**Comment by dejury** [comment]
Okay, can you somehow post me this block anyway? I want to solve this with the HTML purifier, because disabling HTML purifier is not always the best solution.

**Comment by blvckbeard1337** [comment]
Well I improvise the problem here. I copy tag plugin and modify to produce the problem you can test it.

https://jsfiddle.net/qsvnwdrf/1/

**Comment by dejury** [comment]
Thanks for the example.
I think you can make this work with the HTMLpurifier by using the config for
HTML.Allowed or HTML.ForbiddenElements as seen here http://htmlpurifier.org/live/configdoc/plain.html#HTML.Allowed

By setting this up it should make the background-image work. I don't think we should ship this by default.
